### ISSUE TITLE
Serde for Revault transactions

### ISSUE THREAD

**Issue by JSwambo** [re-vault/revault_tx#22]
(Moved from https://github.com/re-vault/revault/pull/20)

If you naively put features = ["use-serde"] in the cargo.toml for bitcoin, will serde's #[derive(Serialize, Deserialize)] work for the ravault tx types?

@darosior : No, it's a newtype: i need to make it a trivial implem (not using #derive).

**Comment by JSwambo** [comment]
But #derive does handle newtypes afaik

**Comment by darosior** [comment]
Yes. You are right it does. However is The PSBT struct is not serde-derived upstream (was actually going to submit a patch!), so we need to implement the trait ourselves.

**Comment by JSwambo** [comment]
Is it not implemented here: https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/psbt/serialize.rs ?

**Comment by darosior** [comment]
Well it does not seem to be.
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by JSwambo** [comment]
Ah I just realized its not 'serde' but consenses::encode

**Comment by darosior** [comment]
Yep, but that means our implem will be straightforward: just call consensus::encode() :-)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by darosior** [comment]
Closing this, as we now have serde support! :tada:
